# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

GET http://localhost:8080/api/10000/paper
Accept: application/json

###

GET http://localhost:8080/api/10001/friend
Accept: application/json

###

GET http://localhost:8080/api/10001/moment
Accept: application/json

###

GET http://localhost:8080/api/10003/stranger
Accept: application/json

###

GET http://localhost:8080/api/10003/agent/10004
Accept: application/json

###

POST http://localhost:8080/api/10000/paper
Content-Type: application/json

{
  "title": "Brand New Paper",
  "content": "A new HTTP Client?"
}

###

DELETE http://localhost:8080/api/10000/paper/4000002
Content-Type: application/json

###

POST http://localhost:8080/api/register
Content-Type: application/json

{
  "username": "betty",
  "password": "22",
  "nickname": "Betty"
}

###

POST http://localhost:8080/api/10005/invite/10000
Content-Type: application/json

"Long time no see, old friend."

###
#Deprecated, use /api/{srcUid}/invite/export/{dstUid} instead.
DELETE http://localhost:8080/api/10005/invite/10000
Content-Type: application/json

###

DELETE http://localhost:8080/api/10005/invite/export/10000
Content-Type: application/json

###

DELETE http://localhost:8080/api/10000/invite/import/10005
Content-Type: application/json

###

GET http://localhost:8080/api/10005/invite/export
Content-Type: application/json

###

GET http://localhost:8080/api/10000/invite/import
Content-Type: application/json

###

POST http://localhost:8080/api/10000/accept/10005
Content-Type: application/json

###

DELETE http://localhost:8080/api/10005/friend/10000
Content-Type: application/json

###

POST http://localhost:8080/api/10002/password
Content-Type: application/json

666

###

POST http://localhost:8080/api/10003/userinfo
Content-Type: application/json

{
  "oldPassword": "666",
  "newPassword": "zhangdeng",
  "nickname": ""
}

###